### ISSUE TITLE
udpipe does not quit gracefully from within rstudio

### ISSUE THREAD

**Issue by RMHogervorst** [bnosac/udpipe#22]
I  think the udpipe package is great! Unfortunately when I cancel the process from within an r session the whole thing crashes. I think it has to do with the way r and the C++ program communicate?

**Comment by jwijffels** [comment]
That is because the implementation sends the vector of text to C++ and loops over the text without giving things back to R untill it finished processing.
If you install the development version of this package from this github repository (version 0.6), I've added an argument `trace `to `udpipe_annotate`. This will print out a message before each trace number of elements of x for which annotation is to be executed, allowing you to see how much of the text is already annotated.
Because this prints out something to the R console, you can also press the RStudio stop button.

```
library(udpipe)
udmodel <- udpipe_download_model(language = "dutch", udpipe_model_repo = "bnosac/udpipe.models.ud")
udmodel <- udpipe_load_model(udmodel$file_model)

data(brussels_reviews, package = "udpipe")
x <- subset(brussels_reviews, language == "nl")
x <- udpipe_annotate(udmodel, x = x$feedback, trace = 10)
## this prints out every 10 text elements to the R console and next you can stop the code with the RStudio stop button if you like
```

**Comment by RMHogervorst** [comment]
Thanks! This is very insightful!
